site_name: OpenSource4Impact
theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.action.edit
  language: en
  palette:
    - scheme: default
  
copyright: Copyright &copy; 2024 &bullet; <a href="/privacy_legal">Legal Notice & Privacy Policy</a> &bullet; <a href="#__consent">Change cookie settings</a>
repo_url: https://github.com/GFA-DIU/OpenSource4Impact
repo_name: OpenSource4Impact
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Introduction:
     - Disclaimer: Introduction/disclaimer.md
     - Open Source in int. Development: Introduction/intro.md
     - About us: Introduction/about_us.md
  - Checklists:
    - pre-project/index.md
    - IT Selection: pre-project/IT_sel_checklist.md
    - Writing ToRs: pre-project/ToR_checklist.md
  - Impressum: privacy_legal.md

extra:
  consent:
    title: Cookie consent
    description: >- 
      Please note that while we do not use cookies, GitHub automatically collects and stores IP addresses for <a href="https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#data-collection">security purposes</a>.
    cookies:
      github: GitHub
    actions:
        - accept

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
  - footnotes

plugins:
  - privacy
